app.upload.dir=/home/thien/uploads/assignment03-user-profile
app.product.page-size=6
app.mail.mock=true
app.mail.host=
app.mail.port=587
app.mail.username=
app.mail.password=
app.mail.from=no-reply@example.com
app.mail.auth=true
app.mail.starttls=true
app.mail.ssl=false
